apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: elasticsearch
  name: elasticsearch
  namespace: elastic-kibana
spec:
  containers:
  - image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    name: elasticsearch
    ports:
    - containerPort: 9200
    resources: 
      requests:
        memory: 1Gi
      limits:
        memory: 1Gi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
