apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kibana
  name: kibana
  namespace: elastic-kibana
spec:
  containers:
  - image: docker.elastic.co/kibana/kibana:8.12.2
    name: kibana
    ports:
    - containerPort: 5601
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
