apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kibana-service
  name: kibana-service
  namespace: elastic-kibana
spec:
  ports:
  - name: 5601-5601
    port: 5601
    protocol: TCP
    targetPort: 5601
    NodePort: 32325
  selector:
    run: kibana
  type: NodePort
status:
  loadBalancer: {}
